name: Générer le jeu du serpent

on:
  # Planifie l'exécution tous les jours à minuit
  schedule:
    - cron: "0 0 * * *"
  # Permet de déclencher manuellement le workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Vérifie le dépôt
      - name: Checkout du dépôt
        uses: actions/checkout@v2

      # Génère l'animation du serpent
      - name: Générer l'animation du serpent
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: votre_nom_utilisateur
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Publie les fichiers générés sur la branche 'output'
      - name: Publier sur la branche output
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
